fix[WIP]: adjust import
According to
https://github.com/git-bug/git-bug/pull/501#issuecomment-2453233379
the package bug has been moved into entities.

Still remaining:

```
mitmanek:git-bug (bug-export *) $ go build
commands/export.go:13:2: undefined: queryOptions
commands/export.go:17:9: undefined: newEnv
commands/export.go:29:13: undefined: loadBackend
commands/export.go:30:13: undefined: closeBackend
commands/export.go:39:33: options.statusQuery undefined (type exportOptions has no field or method statusQuery)
commands/export.go:41:33: options.authorQuery undefined (type exportOptions has no field or method authorQuery)
commands/export.go:43:33: options.participantQuery undefined (type exportOptions has no field or method participantQuery)
commands/export.go:45:33: options.actorQuery undefined (type exportOptions has no field or method actorQuery)
commands/export.go:47:33: options.labelQuery undefined (type exportOptions has no field or method labelQuery)
commands/export.go:61:21: undefined: Env
commands/export.go:47:33: too many errors
mitmanek:git-bug (bug-export *) $
```